### PR TITLE
Adding requirements.yml

### PR DESCRIPTION
**Pull request by andrew-aiken**
**Overall Review of Changes:**
Including requirements.yml 

**Issue Fixes:**
[ Collectiosn requirements file missing #1 ](https://github.com/ansible-lockdown/AMAZON2-CIS/issues/1)

**Enhancements:**
Adding collections requirements.

**How has this been tested?:**
Tested using packer on amazon linux 2 ecs optimized.

### CODE REVIEW

**Comment by andrew-aiken** [comment]
@georgenalen

**Comment by uk-bolly** [comment]
Hi @andrew-aiken 

Thank you for taking the time to raise this PR from the issue that i raised. All help and assistance is very much appreciated.
Is it possible you could extend to work with the meta/main.yml also. It would require the following to be added?

```
collections:
  - community.general
  - community.crypto
  - ansible.posix
```
Many thanks in advance

uk-bolly

**Comment by andrew-aiken** [comment]
Looks like it currently has the collections in meta.

https://github.com/ansible-lockdown/AMAZON2-CIS/blob/a517a2d7a459eb15dc71de891d852863e0db1269/meta/main.yml#L20

**Comment by andrew-aiken** [comment]
Added in another PR

**Pull request closed without merging**
